name: main
on: [workflow_dispatch]
jobs:
  tests:
    # https://github.com/nerrante/cypress-workflows
    uses: nerrante/cypress-workflows/.github/workflows/split.yml@v0.1
    with:
      nE2E: 2
      marge: true
