name: main
on: [push, workflow_dispatch]
jobs:
  tests:
    # https://github.com/nerrante/cypress-workflows
    uses: nerrante/cypress-workflows/.github/workflows/split.yml@v2
    with:
      nE2E: 2
      marge: true
